### ISSUE TITLE
--

### ISSUE THREAD

**Issue by st-mw** [cis3296f24/Section4-ProjectPresentation#18]
--

**Comment by tjmcb** [comment]
Hey!

I think this project has more merit than on first impression! Sure this type of project has been done countless times, but I think a simple and free tool like you said with no downsides is still incredibly valuable, something you know has no strings attached like data collection or advertisements like many free applications on app stores have. That's something I've enjoyed when learning programming: If you don't like the existing solutions out there, you can just make your own! I think spreadsheets are also a clever way of making your goal sheet accessible from anywhere, for example on a google spreadsheet you can check from any device or a page you can print out and put on your wall. 

I know Python but I think more importantly I have an excessive amount of spreadsheet knowledge, I've worked on a python program that's updated a google spreadsheet via the Python gspread library, although I'm sure I would also be able to apply the same principles to offline spreadsheets as well, or both potentially. This project seems like a fun way to organize myself and plot my goals and assignments, and develop a simple but useful tool that could potentially be useful for more people!
